
[log]
type = "console"
level = "debug"

[discovery]
type = "constant"
addresses = [ ]

[cipher]
type = "symmetric"
key = "000102030405060708090a0b0c0d0e0f"

[transport]
type = "direct"
local_address = "127.0.0.1:4001"
request_timeout_ms = 5000
balancer = { type = "dynamic_round_robin" }

[[relay]]
type = "http_static"
address = "127.0.0.1:4200"
header_field = "X-Delix-Service"

[[relay.service]]
name = "slashdot"
address = "216.34.181.45:80"
